const DIVERSIFIEDHEALTHOCCUPATIONS = [
    "abbreviation",
    "abdominal",
    "abduction",
    "abrasion",
    "absorption",
    "abuse",
    "accelerator",
    "acceptance",
    "accreditation",
    "acculturation",
    "acidosis",
    "activities of daily living",
    "acupuncture",
    "acute",
    "addiction",
    "adduction",
    "adenitis",
    "adipose",
    "adolescence",
    "adrenal",
    "advance directive",
    "aerobic",
    "afebrile",
    "affection",
    "agar plate",
    "agent",
    "agglutination",
    "agnostic",
    "air compressor",
    "albino",
    "alginate",
    "alignment",
    "alimentary canal",
    "alopecia",
    "alternative therapy",
    "alveolar process",
    "alveoli",
    "Alzheimer's disease",
    "amalgam",
    "ambulate",
    "amino acid",
    "amputation",
    "anaerobic",
    "analgesia",
    "anaphylactic shock",
    "anatomy",
    "anemia",
    "anesthesia",
    "anger",
    "anorexia",
    "anorexia nervosa",
    "anoxia",
    "antecubital",
    "anterior",
    "anterior teeth",
    "antibody",
    "antibody screen",
    "anticoagulant",
    "antigen",
    "antioxidants",
    "antisepsis",
    "anuria",
    "anus",
    "aorta",
    "aortic valve",
    "apathy",
    "apex",
    "aphasia",
    "apical foramen",
    "apical pulse",
    "apnea",
    "apoplexy",
    "appendicular skeleton",
    "application form",
    "appointment",
    "aquathermia pad",
    "aqueous humor",
    "aromatherapy",
    "arrhythmia",
    "arterial",
    "arteriole",
    "arteriosclerosis",
    "artery",
    "arthritis",
    "asepsis",
    "aspirate",
    "aspirating syringe",
    "aspiration",
    "assault",
    "assistant",
    "associate degree",
    "astigmatism",
    "atheist",
    "atherosclerosis",
    "atrium",
    "atrophy",
    "audiologist",
    "audiometer",
    "auditory acuity",
    "aural temperature",
    "auricle",
    "auscultation",
    "autoclave",
    "automated external defibrillator",
    "autonomic nervous system",
    "autopsy",
    "avulsion",
    "axial skeleton",
    "axilla",
    "Ayer blade",
    "bachelor's degree",
    "backup",
    "bacteria",
    "bandage",
    "bandage scissors",
    "bargaining",
    "Bartholin's glands",
    "basal metabolism",
    "base",
    "base of support",
    "battery",
    "bed cradle",
    "benign",
    "bias",
    "bicuspids",
    "bifurcated",
    "bile",
    "binders",
    "bioethics",
    "biohazardous",
    "biopsy",
    "bioterrorism",
    "bite-wing",
    "bladder",
    "bland diet",
    "block style",
    "blood",
    "blood pressure",
    "blood smear",
    "bloodborne",
    "body",
    "body mechanics",
    "bolus",
    "bowel",
    "Bowman's capsule",
    "brachial",
    "bradycardia",
    "bradypnea",
    "brain",
    "brand name",
    "breast",
    "bronchi",
    "bronchioles",
    "buccal surface",
    "budget",
    "buffer period",
    "bulimarexia",
    "bulimia",
    "burn",
    "burs",
    "calcaneus",
    "calculus",
    "calorie",
    "cancer",
    "cane",
    "capillary",
    "carbohydrate-controlled diet",
    "carbohydrates",
    "carcinogen",
    "carcinoma",
    "cardiac",
    "cardiac arrest",
    "cardiopulmonary",
    "cardiopulmonary resuscitation",
    "cardiovascular",
    "caries",
    "carious lesion",
    "carpal",
    "carpule",
    "catalyst",
    "cataract",
    "catheter",
    "caudal",
    "cavitation",
    "cavity",
    "cell",
    "cell membrane",
    "cellulose",
    "cement",
    "cementum",
    "central nervous system",
    "central processing unit",
    "centrifuge",
    "centrosome",
    "cerebellum",
    "cerebrospinal fl uid",
    "cerebrovascular accident",
    "cerebrum",
    "certifi cation",
    "cervical",
    "cervix",
    "chain of infection",
    "character",
    "charge slip",
    "check",
    "chemical",
    "chemical abuse",
    "chemotherapy",
    "Cheyne-Stokes respirations",
    "chiropractic",
    "cholelithiasis",
    "cholesterol",
    "choroid",
    "chromatin network",
    "chronic",
    "cilia",
    "circumduction",
    "citizenship",
    "clavicle",
    "clean",
    "clear-liquid diet",
    "client",
    "clinic",
    "closed bed",
    "coccyx",
    "cochlea",
    "collection",
    "colon",
    "colostomy",
    "communicable disease",
    "communication",
    "compensation",
    "competent",
    "complementary therapy",
    "complete bed bath",
    "complimentary close",
    "composite",
    "compress",
    "computer-assisted instruction",
    "computerized tomography",
    "concave",
    "confi dential",
    "congenital",
    "conjunctiva",
    "connective tissue",
    "constipation",
    "constrict",
    "consultation",
    "contagious",
    "contamination",
    "contra angle",
    "contract",
    "contracture",
    "contusion",
    "conventional-speed handpiece",
    "convex",
    "convulsion",
    "cornea",
    "cortex",
    "cost containment",
    "Cowper's glands",
    "cranial",
    "cranium",
    "criticism",
    "cross index/reference",
    "cross-match",
    "crown",
    "crust",
    "crutches",
    "cryotherapy",
    "cultural assimilation",
    "cultural diversity",
    "culture",
    "culture specimen",
    "cuspid",
    "custom tray",
    "cyanosis",
    "cystitis",
    "cystoscope",
    "cytoplasm",
    "dangling",
    "day sheet",
    "daydreaming",
    "deciduous teeth",
    "decubitus ulcer",
    "deduction",
    "defamation",
    "defecation",
    "defense mechanism",
    "defi brillate",
    "dehydration",
    "delirium",
    "delusion",
    "dementia",
    "denial",
    "dental chair",
    "dental hygienist",
    "dental light",
    "dentin",
    "dentist",
    "dentition",
    "denture",
    "dependable",
    "deposit slip",
    "depression",
    "dermis",
    "development",
    "diabetes mellitus",
    "diabetic coma",
    "diagnosis",
    "dialysis",
    "diaphoresis",
    "diaphysis",
    "diarrhea",
    "diastole",
    "diastolic pressure",
    "diathermy",
    "diencephalon",
    "dietitian",
    "differential count",
    "digestion",
    "digital",
    "dilate",
    "direct smear",
    "disability",
    "discretion",
    "disease",
    "disinfection",
    "dislocation",
    "disorientation",
    "displacement",
    "distal",
    "distal surface",
    "diuretics",
    "”doctorate",
    "dorsal",
    "dorsal recumbent position",
    "douche",
    "dressing",
    "dry cold",
    "dry heat",
    "duodenum",
    "dyspepsia",
    "dysphagia",
    "dyspnea",
    "dysrhythmia",
    "dystrophy",
    "dysuria",
    "Eearly adulthood",
    "early childhood",
    "echocardiography",
    "edema",
    "ejaculation",
    "ejaculatory duct",
    "electrocardiogram",
    "electroencephalogram",
    "electronic mail",
    "emblem",
    "embolus",
    "embryo",
    "emesis",
    "emotional",
    "empathy",
    "enamel",
    "endocardium",
    "endocrine",
    "endodontics",
    "endogenous",
    "endometrium",
    "endoplasmic reticulum",
    "endorsement",
    "endoscope",
    "endosteum",
    "enema",
    "enthusiasm",
    "entrepreneur",
    "enunciate",
    "enuresis",
    "enzyme",
    "epidemic",
    "epidemiology",
    "epidermis",
    "epididymis",
    "epigastric",
    "epiglottis",
    "epilepsy",
    "epiphysis",
    "epistaxis",
    "epithelial tissue",
    "ergonomics",
    "erythema",
    "erythrocyte",
    "erythrocyte count",
    "erythrocyte sedimentation rate",
    "esophagus",
    "essential nutrients",
    "esteem",
    "ethics",
    "ethnicity",
    "ethnocentric",
    "etiology",
    "eupnea",
    "eustachian tube",
    "eversion",
    "exacerbation",
    "excretion",
    "exocrine",
    "exogenous",
    "expectorate",
    "expiration",
    "extension",
    "external auditory canal",
    "facial surface",
    "facsimile",
    "fainting",
    "Fallopian tubes",
    "false imprisonment",
    "fanfold",
    "fascia",
    "fasting blood sugar",
    "fat",
    "fat-restricted diet",
    "fax",
    "febrile",
    "feces",
    "Federation Dentaire International System",
    "femur",
    "fertilization",
    "fetus",
    "fever",
    "fibula",
    "field",
    "filing",
    "fire extinguisher",
    "firewall",
    "first aid",
    "fixed expenses",
    "flatus",
    "flexion",
    "fomite",
    "fontanel",
    "foramina",
    "Fowler's position",
    "fracture",
    "frontal plane",
    "frostbite",
    "full liquid diet",
    "fungi",
    "gait",
    "gait belt",
    "gallbladder",
    "gastric",
    "gastrostomy",
    "generic name",
    "genes",
    "genital",
    "genome",
    "geriatrics, gerontology",
    "gingiva",
    "glaucoma",
    "glomerulus",
    "glucose",
    "glucose meter",
    "glycosuria",
    "goal",
    "Golgi apparatus",
    "gonads",
    "goniometer",
    "Gram's stain",
    "graphic chart",
    "groin",
    "gross income",
    "growth",
    "gynecology",
    "halitosis",
    "hantavirus",
    "hard copy",
    "hard palate",
    "hardware",
    "heading",
    "Health Insurance Portability and Accountability Act",
    "heart attack",
    "heat cramp",
    "heat exhaustion",
    "heat stroke",
    "helminths",
    "hematemesis",
    "hematocrit",
    "hematology",
    "hematoma",
    "hematopoiesis",
    "hematuria",
    "hemiplegia",
    "hemodialysis",
    "hemoglobin",
    "hemolysis",
    "hemoptysis",
    "hemorrhage",
    "hemorrhoids",
    "hemostat",
    "heparin",
    "hepatitis",
    "high-fiber diet",
    "high-protein diet",
    "high-velocity oral evacuator",
    "HIPAA",
    "histology",
    "holistic health care",
    "home health care",
    "homeostasis",
    "honesty",
    "horizontal recumbent position",
    "hormone",
    "HOSA",
    "hospice",
    "hospital",
    "humerus",
    "hydrocollator packs",
    "hygiene",
    "hyperglycemia",
    "hyperopia",
    "hyperpnea",
    "hypertension",
    "hyperthermia",
    "hypoglycemia",
    "hypotension",
    "hypothalamus",
    "hypothermia",
    "hypothermia blanket",
    "hypoxia",
    "ice bag/collar",
    "idiopathic",
    "ileostomy",
    "ileum",
    "immunity",
    "impaction",
    "impression",
    "incisal surface",
    "incision",
    "incisors",
    "income",
    "incontinent",
    "index",
    "infancy",
    "infarction",
    "infection",
    "inferior",
    "infl ammation",
    "informed consent",
    "ingestion",
    "inguinal",
    "inhalation",
    "initiative",
    "input",
    "inquiry",
    "insertion",
    "inside address",
    "inspiration",
    "insulin",
    "insulin shock",
    "insurance form",
    "intake and output",
    "integrative health care",
    "integumentary",
    "interactive video",
    "intercostal",
    "Internet",
    "interproximal space",
    "intestine",
    "intradermal",
    "intramuscular",
    "intravenous",
    "intubate",
    "invasion of privacy",
    "invasive",
    "inversion",
    "involuntary",
    "iris",
    "ischemia",
    "isolation",
    "jackknife position",
    "jaundice",
    "jejunum",
    "job interview",
    "joint",
    "kcal-controlled diet",
    "ketone",
    "ketonuria",
    "kidney",
    "kilocalorie",
    "kilojoule",
    "knee-chest position",
    "labia majora",
    "labia minora",
    "labial surface",
    "laboratory",
    "laceration",
    "lacrimal",
    "lactation",
    "lacteal",
    "lancet",
    "laryngeal mirror",
    "larynx",
    "late adulthood",
    "late childhood",
    "lateral",
    "lead",
    "leadership",
    "ledger card",
    "left lateral position",
    "legal",
    "legal disability",
    "lens",
    "lethargy",
    "letterhead",
    "leukocyte",
    "leukocyte count",
    "liability",
    "libel",
    "licensure",
    "life stages",
    "ligament",
    "light diet",
    "line angle",
    "liner",
    "lingual surface",
    "listen",
    "lithotomy position",
    "liver",
    "living will",
    "low-cholesterol diet",
    "low-protein diet",
    "low-residue diet",
    "low-speed handpiece",
    "lung",
    "lymph",
    "lymph node",
    "lymphatic duct",
    "lymphatic vessels",
    "lysosomes",
    "macule",
    "magnetic resonance imaging",
    "mainframe computer",
    "malignant",
    "malnutrition",
    "malpractice",
    "mammogram",
    "managed care",
    "mandible",
    "master's degree",
    "mastication",
    "Material Safety Data Sheets",
    "matriarchal",
    "maxilla",
    "meatus",
    "mechanical lift",
    "medial",
    "Medicaid",
    "medical history",
    "medical record",
    "Medicare",
    "medication",
    "Medigap policy",
    "medulla",
    "medulla oblongata",
    "medullary canal",
    "meiosis",
    "melanin",
    "memorandum",
    "meninges",
    "menopause",
    "mental",
    "mesial surface",
    "metabolism",
    "metacarpal",
    "metastasis",
    "metatarsal",
    "microbiology",
    "microcomputer",
    "microorganism",
    "microscope",
    "micturate",
    "midbrain",
    "middle adulthood",
    "midsagittal",
    "midstream specimen",
    "minerals",
    "mitered corner",
    "mitochondria",
    "mitosis",
    "mitral valve",
    "model",
    "modifi ed  block",
    "moist cold",
    "moist heat",
    "molars",
    "motivated",
    "mouth",
    "mucus",
    "muscle tissue",
    "muscle tone",
    "myocardial infarction",
    "myocardium",
    "myopia",
    "myth",
    "nasal cavity",
    "nasal septum",
    "nasogastric tube",
    "nausea",
    "necrosis",
    "need",
    "needle holder",
    "negligence",
    "neonate",
    "neoplasm",
    "nephritis",
    "nephron",
    "nerve",
    "nerve tissue",
    "net income",
    "network",
    "neurology",
    "neuron",
    "nocturia",
    "noninvasive",
    "nonpathogen",
    "nonverbal",
    "nose",
    "nosocomial",
    "nucleolus",
    "nucleus",
    "nutrition",
    "nutritional status",
    "obese",
    "objective observation",
    "observation",
    "obstetrics",
    "occlusal surface",
    "occult",
    "occult blood",
    "occupational therapy",
    "occupied bed",
    "odontology",
    "olfactory",
    "oliguria",
    "ombudsman",
    "Omnibus Budget Reconciliation Act",
    "oncology",
    "open bed",
    "ophthalmologist",
    "ophthalmology",
    "ophthalmoscope",
    "opportunistic infection",
    "optician",
    "optometrist",
    "oral",
    "oral cavity",
    "oral hygiene",
    "oral-evacuation system",
    "organ",
    "organ of Corti",
    "organelles",
    "origin",
    "originator",
    "orthodontics",
    "orthopedics",
    "orthopnea",
    "orthotist",
    "os coxae",
    "ossicles",
    "osteopathy",
    "osteoporosis",
    "ostomy",
    "otoscope",
    "output",
    "ovary",
    "palate",
    "palliative",
    "pallor",
    "palpation",
    "pancreas",
    "pandemic",
    "panoramic",
    "Papanicolaou test",
    "papule",
    "paraffin wax treatment",
    "paralysis",
    "paraplegia",
    "parasite",
    "parasympathetic",
    "parathyroid",
    "parenteral",
    "paresis",
    "partial bath",
    "patella",
    "pathogen",
    "pathology",
    "pathophysiology",
    "patience",
    "patients' rights",
    "patriarchal",
    "patriotism",
    "payee",
    "pediatrics",
    "pedodontics",
    "pegboard system",
    "pelvic",
    "penis",
    "percussion",
    "percussion hammer",
    "periapical",
    "pericardium",
    "perineum",
    "periodontal ligament",
    "periodontics",
    "periodontium",
    "periosteum",
    "peripheral",
    "peristalsis",
    "peritoneal",
    "permanent teeth",
    "personal hygiene",
    "personal protective equipment",
    "perspiration",
    "pH",
    "phalanges",
    "pharmacology",
    "pharynx",
    "phlebitis",
    "phlebotomist",
    "physiatrist",
    "physical",
    "physical therapy",
    "Physicians' Desk Reference",
    "physiological needs",
    "physiology",
    "pineal",
    "pinna",
    "pituitary",
    "placenta",
    "plane",
    "plaque",
    "plasma",
    "platelet",
    "pleura",
    "podiatrist",
    "point angle",
    "poisoning",
    "polycythemia",
    "polydipsia",
    "polyphagia",
    "polyuria",
    "pons",
    "positron emission tomography",
    "posterior",
    "posterior teeth",
    "postmortem care",
    "postoperative",
    "postpartum",
    "Power of Attorney",
    "prefi x",
    "prejudice",
    "prenatal",
    "preoperative",
    "pressure ulcer",
    "primary teeth",
    "privileged communications",
    "proctoscope",
    "prognosis",
    "projection",
    "pronation",
    "”prone position",
    "prophylactic",
    "prophylaxis angle",
    "prostate gland",
    "prosthesis",
    "prosthodontics",
    "protective isolation",
    "protein",
    "protoplasm",
    "protozoa",
    "proximal",
    "pruritus",
    "psychiatry",
    "psychology",
    "psychosomatic",
    "puberty",
    "pulmonary",
    "pulmonary valve",
    "pulp",
    "pulse",
    "pulse deficit",
    "pulse oximeter",
    "pulse pressure",
    "puncture wound",
    "pupil",
    "pustule",
    "pyrexia",
    "pyuria",
    "quadriplegia",
    "race",
    "radial deviation",
    "radiograph",
    "radiology",
    "radiolucent",
    "radiopaque",
    "radius",
    "rale",
    "random access memory",
    "range of motion",
    "rate",
    "rationalization",
    "read only memory",
    "reagent strip",
    "reality orientation",
    "recall",
    "receipt",
    "rectal, rectum",
    "rectal tube",
    "red blood cell",
    "red marrow",
    "reference initials",
    "refractometer",
    "registration",
    "rehabilitation",
    "religion",
    "remission",
    "repression",
    "resident",
    "resistant",
    "respiration",
    "responsibility",
    "restoration",
    "restraints",
    "résumé",
    "retina",
    "retractor",
    "reverse isolation",
    "rheostat",
    "rhythm",
    "ribs",
    "rickettsiae",
    "root",
    "rotation",
    "rubber base",
    "Ssafety standards",
    "saliva ejector",
    "salivary glands",
    "salutation",
    "sarcoma",
    "satisfaction",
    "scalpel",
    "scapula",
    "sclera",
    "screen",
    "scrotum",
    "search engine",
    "sebaceous gland",
    "secretion",
    "seizure",
    "self-actualization",
    "self-esteem",
    "self-motivation",
    "semicircular canals",
    "seminal vesicle",
    "senile lentigines",
    "senility",
    "sensitive",
    "sensitivity",
    "sepsis",
    "septum",
    "serrated",
    "sharps container",
    "shock",
    "sigmoidoscope",
    "sign",
    "signature",
    "Sims' position",
    "sinus",
    "sitz bath",
    "skeleton",
    "skill",
    "skin puncture",
    "slander",
    "small intestine",
    "smear",
    "Snellen charts",
    "social",
    "sodium hypochlorite",
    "sodium-restricted diet",
    "soft diet",
    "soft palate",
    "software",
    "specific gravity",
    "speculum",
    "sphygmomanometer",
    "spinal",
    "spinal cord",
    "spirituality",
    "spleen",
    "splinter forceps",
    "sprain",
    "sputum",
    "standard precautions",
    "statement-receipt",
    "statistical data",
    "stereotyping",
    "sterile",
    "sterile field",
    "sterilization",
    "sternum",
    "stethoscope",
    "stoma",
    "stomach",
    "stool",
    "strain",
    "stress",
    "stroke",
    "subcutaneous",
    "subcutaneous fascia",
    "subjective observation",
    "sublingual",
    "succedaneous teeth",
    "sudoriferous gland",
    "suffix",
    "suicide",
    "superior",
    "supination",
    "”supine position",
    "suppository",
    "suppression",
    "surgery",
    "surgical hose",
    "surgical scissors",
    "surgical shave",
    "suture",
    "suture-removal set",
    "sympathetic",
    "symptom",
    "syncope",
    "system",
    "systemic",
    "systole",
    "systolic pressure",
    "tachycardia",
    "tachypnea",
    "tactful",
    "tarsal",
    "tartar",
    "teamwork",
    "technician",
    "technologist",
    "teeth",
    "temperature",
    "temporal temperature",
    "temporary",
    "tendon",
    "tension",
    "terminal illness",
    "testes",
    "thalamus",
    "therapeutic diet",
    "therapy",
    "thermometer",
    "thermotherapy",
    "thoracic",
    "thoracic duct",
    "thrombocyte",
    "thrombus",
    "thymus",
    "thyroid",
    "tibia",
    "time management",
    "tissue",
    "tissue forceps",
    "tongue",
    "tonometer",
    "tonsil",
    "tort",
    "tourniquet",
    "towel clamps",
    "trachea",
    "tracheostomy",
    "transdermal",
    "transfer belt",
    "transfusion",
    "transverse plane",
    "Trendelenburg position",
    "triage",
    "tricuspid valve",
    "tri-flow syringe",
    "trifurcated",
    "tuning fork",
    "24-hour urine specimen",
    "tympanic membrane",
    "typing and crossmatch",
    "ulcer",
    "ulna",
    "ulnar deviation",
    "ultrasonic unit",
    "ultrasonography",
    "ultra-speed handpiece",
    "umbilicus",
    "Universal/National Numbering System",
    "uremia",
    "ureter",
    "ureterostomy",
    "urethra",
    "urinalysis",
    "urinary-drainage unit",
    "urinary meatus",
    "urinary sediments",
    "urinate",
    "urine",
    "urinometer",
    "urology",
    "urticaria",
    "uterus",
    "vaccine",
    "vagina",
    "vaginal irrigation",
    "variable expense",
    "varicose",
    "vas deferens",
    "vascular",
    "vasoconstriction",
    "vasodilation",
    "vector",
    "vein",
    "venipuncture",
    "venous",
    "ventilation",
    "ventral",
    "ventricle",
    "venule",
    "vertebrae",
    "vertigo",
    "vesicle",
    "vestibule",
    "veterinary",
    "villi",
    "virus",
    "visceral",
    "visual acuity",
    "vital signs",
    "vitamins",
    "vitreous humor",
    "void",
    "volume",
    "voluntary",
    "vomit",
    "vulva",
    "walker",
    "warm-water bag",
    "wellness",
    "wheezing",
    "white blood cell",
    "withdrawal",
    "word root",
    "Workers' Compensation",
    "wound",
    "xiphoid process",
    "yellow marrow",
];

export default DIVERSIFIEDHEALTHOCCUPATIONS;