export const BODYSTRUCTURESANDFUNCTIONS = [
    "abdomen",
    "abdominal cavity",
    "abdominalpelvic cavity",
    "abduction",
    "abscess",
    "absorption",
    "accomodation",
    "acetylcholine",
    "acid",
    "acne vulgaris",
    "acquired immunity",
    "acquired immunodeficiency syndrome",
    "acromegaly",
    "action potential",
    "active acquired immunity",
    "active transport",
    "acute glomerulonephritis",
    "acute kidney failure",
    "addison's disease",
    "adduction",
    "adenitis",
    "adenoids",
    "adenosine triphosphate (ATP)",
    "adequate intake (AI)",
    "adipose tissue",
    "adrenal gland",
    "adrenalin",
    "adrenocorticotropic hormone (ACTH)",
    "afferent arteriole",
    "afferent arteriole",
    "afferent lymphatic vessel",
    "afferent neuron",
    "agent",
    "agranulcyte",
    "airborne transmission",
    "albumin",
    "albuminuria",
    "aldosterone",
    "alimentary canal",
    "alkali",
    "all or none law",
    "allergen",
    "alopecia",
    "alveolar sacs",
    "alveoli",
    "Alzheimer's disease",
    "amblyopia",
    "amenorrhea",
    "amino acid",
    "amniocentesis",
    "amphiarthrosis",
    "amylase",
    "amylopsin",
    "anabolism",
    "analgesic",
    "analphase",
];