export const BODYSTRUCTURESANDFUNCTIONS = [
    "abdomen",
    "abdominal cavity",
    "abdominalpelvic cavity",
    "abduction",
    "abscess",
    "absorption",
    "accomodation",
    "acetylcholine",
    "acid",
    "acne vulgaris",
    "acquired immunity",
    "acquired immunodeficiency syndrome",
    "acromegaly",
    "action potential",
    "active acquired immunity",
    "active transport",
    "acute glomerulonephritis",
    "acute kidney failure",
    "addison's disease",
    "adduction",
    "adenitis",
    "adenoids",
    "adenosine triphosphate (ATP)",
    "adequate intake (AI)",
    "adipose tissue",
    "adrenal gland",
    "adrenalin",
    "adrenocorticotropic hormone (ACTH)",
    "afferent arteriole",
    "afferent arteriole",
    "afferent lymphatic vessel",
    "afferent neuron",
    "agent",
    "agranulcyte",
    "airborne transmission",
    "albumin",
    "albuminuria",
    "aldosterone",
    "alimentary canal",
    "alkali",
    "all or none law",
    "allergen",
    "alopecia",
    "alveolar sacs",
    "alveoli",
    "Alzheimer's disease",
    "amblyopia",
    "amenorrhea",
    "amino acid",
    "amniocentesis",
    "amphiarthrosis",
    "amylase",
    "amylopsin",
    "anabolism",
    "analgesic",
    "analphase",
    "anaphylatic shock",
    "anaphylaxis",
    "anatomical position",
    "anatomy",
    "androgen",
    "anemia",
    "aneurysm",
    "angina pectoris",
    "angioplasty",
    "anorexia nervosa",
    "antagonist",
    "anterior",
    "anterior chamber",
    "anterior nares",
    "anterior pituitary lobe",
    "antrax",
    "antibody",
    "anticoagulunt",
    "anticonvulsant",
    "antidiuretic hormone",
    "antigen",
    "antiprothrombin",
    "antithromboplastin",
    "annuria",
    "anus",
    "anvil",
    "aorta",
    "aortic semilunar valve",
    "apex",
    "aphasia",
    "aplastic anemia",
    "apnea",
    "aponeurosis",
    "aptosis",
    "appendicitis",
    "appendicular skeleton",
    "aqueous humor",
    "arachnoid",
    "areola",
    "areolar tissue",
    "arrector pili muscle",
    "arrhythmia",
    "arteriole",
    "arteriosclerosis",
    "artery",
    "arthritis",
    "articular cartilage",
    "artificial acquired ammunity",
    "artificial insemenation",
    "asbestosis",
    "ascending colon",
    "ascites",
    "associative neuron",
    "asthma",
    "astigmatism",
    "atelectais",
    "atherosclerosis",
    "athlete's foot",
    "atlas",
    "atom",
    "atrioventricular (AV) node",
    "atrioventricular bundle",
    "atrium",
    "atrophy",
    "auricle",
    "autoimmunne disorder",
    "autoimmunity",
    "autonomic nervous system",
    "avascular",
    "axial skeleton",
    "axilla",
    "axillary node",
    "axis",
    "axon",
    "bacteria",
    "bactericidal",
    "ball-and-socket joint",
    "balloon surgery",
    "Bartholin's gland",
    "basal cell carcinoma",
    "basal metabolic rate (BMR)",
    "base",
    "basophil",
    "Bell's palsy",
    "belly",
    "benign prostatic hypertrophy (BPH)",
    "benign",
    "biceps",
    "bicuspid",
    "bicuspid (mitral) valve",
    "bile",
    "bilirubin",
    "biochemistry",
    "biofeedback",
    "biological agent",
    "biology",
    "biomarker",
    "blind spot",
    "blood-brain barrier",
    "B-lymphocyte",
    "body mass index (BMI)",
    "Bowman's capsule",
    "brachial artery",
    "bradycardia",
    "brainstem",
    "breast",
    "bronchiectasis",
    "bronchiole",
    "bronchitis",
    "bronchoscopy",
    "bronchus",
    "buccal cavity",
    "buffer",
    "bulbourethral gland",
    "bulimia",
    "burn",
    "bursa sacs",
    "calcaneus",
    "calcitonin",
    "calorie",
    "calyx",
    "cancer",
    "canine",
    "capillary",
    "carbohydrate",
    "carbon monoxide (CO) poisoning",
    "cardiac arrest",
    "cardiac catherization",
    "cardiac muscle",
    "cardiac output",
    "cardiac sphincter",
    "cardiac stents",
    "cardiopulmonary circulation",
    "cardiopulmonary resuscitation (CPR)",
    "cardiotonic",
    "caries",
    "carotid",
    "carpal",
    "carpal tunnel syndrome",
    "carrier",
    "cartilage",
    "catabolism",
    "cataract",
    "caudal",
    "cecum",
    "cell",
    "cell membrane",
    "cellular respiration or oxidation",
    "central nervous system",
    "centrioles",
    "centrosome",
    "cerebellum",
    "cerebral aqueduct",
    "cerebral cortex",
    "cerebral hemmorrhage",
    "cerebral palsy",
    "cerebral vasular accident (CVA)",
    "cerebral ventricles",
    "cerebrospinal fluid",
    "cerebrum",
    "cerumen",
    "cervical vertebrae",
    "cervix",
    "chemical agent",
    "chemistry",
    "chlamydia",
    "cholecystitis",
    "cholesterol",
    "chordae tendinae",
    "choronic villi sampling",
    "choroid coat",
    "choroid plexus",
    "chromatid",
    "chromatin",
    "chromosomal mutation",
    "chromosome",
    "chronic glonerulonephritis",
    "chronic obstructive pulmonary disease (COPD)",
    "chronic renal failure",
    "chyme",
    "cicatrix",
    "cilia",
    "ciliary body",
    "circumcision",
    "circumduction",
    "cirrhosis",
    "claudication",
    "clavicle",
    "cleansing",
    "clean wound",
    "clitoris",
    "clotting time",
    "coagulation",
    "coccyx",
    "cochlea",
    "cochlear duct",
    "coenzyme",
    "coitus",
    "collagen",
    "collecting tubule",
    "colon",
    "colon cancer",
    "color blindness",
    "colostomy",
    "common bile duct",
    "common carotid artery",
    "common cold",
    "comparative anatomy",
    "complete proteins",
    "compounds",
    "compromised host",
    "conduction defect",
    "cones",
    "congenital disorder",
    "cogenital heart defect",
    "congestive heart failure",
    "conjunctivitis",
    "connective tissue",
    "constipation",
    "contact transmission",
    "contractability",
    "convalescent stage",
    "Cooley's anemia",
    "corium",
    "cornea",
    "corona radiata",
    "coronal plane",
    "coronary",
    "coronary artery",
    "coronary artery disease (CAD)",
    "coronary bypass",
    "coronary circulation",
    "coronary sinus",
    "corpus callosum",
    "corpus luteum",
    "cortex",
    "coughing",
    "Cowpeder's gland", 
    "cranial",
    "cranial cavity",
    "cranial nerves",
    "cretinism",
    "crosseye",
    "crown",
    "cryosurgery",
    "cryptochidism",
    "Cushing's syndrome",
    "cutaneous",
    "cyanosis",
    "cystic duct",
    "cystic fibrosis",
    "cycstitis",
    "cytology",
    "cytoplasm",
    "cytoskeleton",
    "deciduous",
    "decubitus ulcer",
    "deep",
    "defecation",
    "defibrillator",
    "dehydration",
    "deltoid",
    "dementia",
    "dendrite",
    "dentin",
    "deoxygenate",
    "deoxyribonucleic acid(DNA)",
    "dermatitis",
    "dermatology",
    "dermis",
    "descending colon",
    "detached retina",
    "developmental anatomy",
    "deviated nasal septun",
    "diabetes insipidus",
    "diabetes mellitus",
    "dialysis",
    "dialyzer",
    "diarrhea",
    "diarthrosis",
    "diastole",
    "diastolic blood pressure",
    "diencephalon",
    "diffusion",
    "digesstion",
    "dilator muscle",
    "diphtheria",
    "diplopia",
    "disaccharide",
    "disease",
    "disinfection",
    "dislocaton",
    "distal",
    "distal convoluted tubule",
    "diuretic",
    "diverticulitis",
    "diverticulosis",
    "dorsal",
    "dorsal cavity",
    "dorsalis pedis artery",
    "Down syndrome",
    "Duchenne's musculardystrophy",
    "ductus arteriosus",
    "ductus deferens or vas deferens",
    "ductus venosus",
    "duodenum",
    "dura matter",
    "dwarfism",
    "dysmenorrhea",
    "dysphasia",
    "dysplasia",
    "dyspnea",
    "dysuria",
    "Ear wax",
    "ectropic",
    "ectropic pregnancy",
    "eczema",
    "edema",
    "effector",
    "efferent neuron",
    "ejaculatory ducts",
    "elasticity",
    "elastin",
    "electrocardigram (ECG or EKG)",
    "electrolytes",
    "electromyograph (EMG)",
    "electron",
    "element",
    "embolism",
    "embryo",
    "embryology",
    "emphysema",
    "enamel",
    "encephalitis",
    "endocarditis",
    "endocardium",
    "endocrine gland",
    "endocrinology",
    "endometriosis",
    "endometrium",
    "endoplasmic recticulum",
    "endosteum",
    "energy",
    "enteritis",
    "enzyme",
    "eosinophil",
    "epidermis",
    "epididymis",
    "epididymitis",
    "epigastric",
    "epiglottis",
    "epilepsy",
    "epinephrine",
    "epiphysis",
    "episiotomy",
    "epithelial tissue",
    "equilibrium",
    "ergonomics",
    "erythroblastosis fetalis",
    "erythrocyte",
    "erythropiesis",
    "eschar",
    "esophagus",
    "essential amino acids",
    "essential tremors",
    "estrogen",
    "ethmoid",
    "eupnea",
    "eustachian tube",
    "excitability",
    "exocrine gland",
    "exophthalmos",
    "expiration",
    "exiratory reserve volume (ERV)",
    "extensibility",
    "extension",
    "external",
    "external respiration",
    "extracellular fluid",
    "extracorporeal shockwave lithotripsy (ESWL)",
    "extrinsic muscle",
    "eye strain",
    "fallopian tube",
    "farsightedness",
    "fasciae",
    "fat",
    "feces",
    "femoral artery",
    "femoral nerve",
    "femur",
    "fertilization",
    "fetal circulation",
    "fetus",
    "fiber",
    "fibrillation",
    "fibrin",
    "fibrinogen",
    "fibroid tumor",
    "fibromyalgia",
    "fibula",
    "filtrate",
    "filtration",
    "fimbrae",
    "first degree burn",
    "fissures",
    "fitula",
    "flahella",
    "flatfeet",
    "flatulence",
    "flexion",
    "flexor",
    "flora",
    "follicle-stimualting hormone (FSH)",
    "fomite",
    "fontanel",
    "foramen",
    "foramen ovale",
    "foreskin",
    "fourth ventricle",
    "fovea centralis",
    "fracture",
    "frontal",
    "frontallobe",
    "functional residual capacity",
    "fundus",
    "fungi",
    "gallbladder",
    "gallstones",
    "gamete",
    "gamma globulin",
    "ganglion",
    "gangrene",
    "gastric",
    "gastric glands",
    "gastric mucosa",
    "gastritis",
    "gastroenteritis",
    "gastroesophageal reflux disease(GERD)",
    "gene",
    "gene mutation",
    "genetic counseling",
    "genetic disorder",
    "genetic engineering",
    "genetics",
    "genital herpes",
    "genital warts",
    "genitals",
    "germ cell",
    "germinal center",
    "gestation",
    "gigantism",
    "gingiva",
    "gingivitis",
    "glans penis",
    "glaucoma",
    "gliding joint",
    "globin",
    "globulin",
    "glomerulonephritis",
    "glomerulus",
    "glottis",
    "glucagon",
    "glucocorticoid",
    "glucose",
    "gluteal",
    "glycogen",
    "goiter",
    "Golgi apparatus",
    "gonads",
    "gonnorhea",
    "gout",
    "graafian follicle",
    "graft",
    "granulation",
    "granulocyte",
    "greater omentum",
    "gross anatomy",
    "growth hormone (GH)",
    "gyri",
    "hair follicle",
    "hammer",
    "hammer toe",
    "heart block",
    "heart failure",
    "heartburn",
    "helminth",
    "hematoma",
    "hematopoeisis",
    "hematuria",
    "hemiplegia",
    "hemoccult",
    "hemodialysis",
    "hemoglobin",
    "hemolysis",
    "hemophilia",
    "hemorrhoids",
    "heparin",
    "hepatic duct",
    "hepatic vein",
    "hepatitis",
    "Hering-Brewer reflex",
    "hernia",
    "herpes",
    "herpes zoster",
    "hiatal hernia",
    "hiccough",
    "high density lipoprotein",
    "hilum",
    "hinge joint",
    "histamine",
    "histology",
    "hives",
    "Hodgkin’s disease",
    "homeostasis",
    "hormone",
    "host",
    "human immunodeficiency virus",
    "humerus",
    "humoral immunity",
    "Huntington’s disease",
    "hyaline",
    "hydrocephalus",
    "hydronephrosis",
    "hydroxide",
    "hymen",
    "hyoid",
    "hyperglycemia",
    "hyperplasia",
    "hyperopia",
    "hyperpnea",
    "hypersensitivity",
    "hypertension",
    "hyperthermia",
    "hyperthyroidism",
    "hypertonic solution",
    "hypertrophy",
    "hyperventilation",
    "hypogastric",
    "hypoglycemia",
    "hypoperfusion",
    "hypotension",
    "hypothalamus",
    "hypothermia",
    "hypothyroidism",
    "hypotonic solution",
    "hysterectomy",
    "ideopathic",
    "ileocecal valve",
    "ileum", 
    "illness stage", 
    "immunity", 
    "immunization", 
    "immunoglobulin", 
    "impetigo", 
    "impotence", 
    "incisor", 
    "incomplete proteins", 
    "incontinence", 
    "incubation stage", 
    "incus", 
    "infectious mononucleosis", 
    "inferior", 
    "inferior concha", 
    "infertility", 
    "inflammation", 
    "inflammatory bowel disease", 
    "influenza", 
    "inguinal hernia", 
    "insertion", 
    "inspiration",
    "inspiratory reserve volume(IRV)", 
    "insulin", 
    "integument", 
    "integumentary system", 
    "intercostal muscles", 
    "interferon", 
    "internal", 
    "internal respiration", 
    "interneuron", 
    "interphase", 
    "interstitial cell-stimulating hormone(ICSH)", 
    "interstitial fluid", 
    "interstitial tissue", 
    "interventricular foramen", 
    "intestinal mucosa", 
    "intracellular fluid", 
    "intramuscular", 
    "intrinsic muscle", 
    "in-vitro fertilization(IVF)", 
    "ion", 
    "ionize", 
    "iris", 
    "iron-deficiency anemia", 
    "irritability", 
    "islets of Langerhans", 
    "isometric", 
    "isotonic solution", 
    "isotonic",
    "isotope",
    "jaundice", 
    "jejunum", 
    "joint",
    "keratin", 
    "kidney", 
    "kidney stones", 
    "kilocalorie", 
    "kinetic energy", 
    "kyphosis",
    "labia majora",
    "labia minora",
    "lacrimal",
    "lacteals",
    "laparoscope",
    "laparoscopy",
    "laryngitis",
    "larynx",
    "lateral",
    "lateral ventricles",
    "left lymphatic duct",
    "left ventricle",
    "lens",
    "lethal gene",
    "leukemia",
    "leukocyte",
    "leukocytosis",
    "leukopenia",
    "lice", 
    "life function",
    "ligament",
    "limbic lobe",
    "lingual",
    "lipase",
    "lipid",
    "lithotripsy",
    "liver",
    "loop of Henle",
    "lordosis",
    "low density lipoprotein",
    "lubb dupp sound",
    "lumbar",
    "lumbar puncture",
    "lumbar vertebrae",
    "lumpectomy",
    "lupus",
    "luteinizing hormone",
    "lymph",
    "lymph nodes",
    "lymph vessels", 
    "lymphadenitis", 
    "lymphatic system", 
    "lymphocyte", 
    "lymphokines", 
    "lysosome", 
    "macrophage", 
    "macula lutea", 
    "macular degeneration", 
    "malignant melanoma", 
    "malleus", 
    "mammogram", 
    "mandible", 
    "mastectomy", 
    "masticate", 
    "mastication", 
    "matrix", 
    "matter",
    "maxilla", 
    "medial", 
    "mediastinum", 
    "medulla", 
    "medulla oblongata", 
    "medullary canal", 
    "meiosis",
    "melanin", 
    "melanocytes", 
    "melatonin", 
    "membrane", 
    "membrane excitability", 
    "memory", 
    "menarche", 
    "Meniere's disease", 
    "meninges", 
    "meningitis", 
    "menopause", 
    "menstrual cycle", 
    "menstruation", 
    "mesentery", 
    "metabolism", 
    "metacarpal", 
    "metaphase", 
    "metastasis", 
    "metatarsal", 
    "metric system", 
    "microscopic anatomy", 
    "midsagittal plane", 
    "mineral", 
    "mineralocorticoids", 
    "miotic", 
    "mitochondria", 
    "mitosis",
    "mitral valve prolapse",
    "mixed nerve",
    "mode of transmission",
    "molar",
    "molecule",
    "mongolism",
    "monocyte",
    "monokines",
    "monosaccharide",
    "mons pubis",
    "morphology",
    "motor nerve",
    "motor neuron",
    "motor unit",
    "mucosa",
    "mucous membrane",
    "multicellular",
    "multiple sclerosis (MS)",
    "murmur",
    "muscle fatigue",
    "muscle spasm",
    "muscle tissue",
    "muscle tone",
    "muscular dystrophy",
    "mutagenic agent",
    "mutation",
    "myalgia",
    "myasthenia gravis",
    "myelin",
    "myelin sheath",
    "myeloblast",
    "myocardial infection",
    "myocarditis",
    "myocardium",
    "myometrium",
    "myopia",
    "myringotomy",
    "myxedema",
    "nasal",
    "nasal cavity",
    "nasal polyps",
    "nasal septum",
    "natural acquired immunity",
    "natural immunity",
    "nearsightedness",
    "neck of tooth",
    "necrosis",
    "negative feedback",
    "neoplasm",
    "malignant",
    "nephron",
    "nervous tissue",
    "neuralgia",
    "neuritis",
    "neurogenic bladder",
    "neuroglia",
    "neurology",
    "neuromuscular junction",
    "neuron",
    "neutralization",
    "neutron",
    "neutrophil",
    "night blindness",
    "nocturia",
    "norepinephrine",
    "nosocomial infection",
    "nuclear membrane",
    "nucleic acid",
    "nucleolus",
    "nucleoplasm",
    "nucleus",
    "nutrient",
    "nystagmus",
    "obesity",
    "occipital",
    "occipital lobe",
    "olecranon process",
    "olfactory",
    "olfactory nerve",
    "oliguria",
    "oogenesis",
    "ophthalmic",
    "optic disc",
    "oral cavity",
    "orbital cavity",
    "orchitis",
    "organ",
    "organelle",
    "organ of Corti",
    "organ system",
    "organic catalyst",
    "organic compound",
    "organic food",
    "origin",
    "oropharynx",
    "orthopnea",
    "osmoreceptor",
    "osmosis",
    "osmotic pressure",
    "osseous tissue",
    "ossification",
    "osteoarthritis",
    "osteoblast",
    "osteoclast",
    "osteocyte",
    "osteomyelitis",
    "osteoporosis",
    "osteosarcoma",
    "otitis media",
    "otosclerosis",
    "ova",
    "ovary",
    "oviduct",
    "ovulation",
    "ovarian follicle cel",
    "oxidation",
    "oxygenate",
    "oxyhemoglobin",
    "oxytocin",
    "pacemaker",
    "palatine",
    "palpitation",
    "pancreas",
    "pancreatitis",
    "Pap or Papanicolaou smear",
    "papillae",
    "papilloma",
    "paraplegia",
    "parasympathetic system",
    "parathormone",
    "parathyroid gland",
    "paresthesia",
    "parietal",
    "parietal lobe",
    "parietal membrane",
    "Parkinson’s disease",
    "parotid salivary gland",
    "passive acquired immunity",
    "passive transport",
    "patella",
    "pathogenic",
    "pathogenicity",
    "pectoral",
    "pelvic cavity",
    "pelvic girdle",
    "pelvic inflammatory disease",
    "pelvis",
    "penile shaft",
    "penis",
    "peptic ulcer",
    "pericardial membrane",
    "pericarditis",
    "pericardium",
    "perineum",
    "periodontal membrane",
    "periosteum",
    "perioxisome",
    "peripheral",
    "peripheral nervous system",
    "peripheral vascular disease",
    "peristalsis",
    "peritoneal dialysis",
    "peritoneal lining",
    "peritoneal membrane",
    "peritoneum",
    "peritonitis",
    "pernicious anemia",
    "pertussis",
    "phagocyte",
    "phagocytosis",
    "phalanges",
    "pharyngitis",
    "pharynx",
    "phase",
    "phenylketonuria",
    "phlebitis",
    "phospholipids",
    "phrenic nerve",
    "physical agent",
    "physiology",
    "physiotherapy",
    "pia mater",
    "pineal gland",
    "pinna",
    "pinocytic vessel",
    "pinocytosis",
    "pituitary gland",
    "pivot joint",
    "planes",
    "plasma",
    "plasma membrane",
    "pleura",
    "pleural fluid",
    "pleural membrane",
    "pleurisy",
    "plexus",
    "pneumonia",
    "pneumothorax",
    "poliomyelitis",
    "polycythemia",
    "polydipsia",
    "polyphagia",
    "polysaccharide",
    "polyuria",
    "pons",
    "popliteal",
    "popliteal artery",
    "portal circulation",
    "portal of entry",
    "portal of exit",
    "portal vein",
    "posterior",
    "posterior chamber",
    "posterior pituitary lobe",
    "potential energy",
    "premenstrual syndrome",
    "prepuce",
    "presbycusis",
    "presbyopia",
    "primary repair",
    "prime mover",
    "prodromal stage",
    "progesterone",
    "pregnancy",
    "prolactin hormone",
    "pronation",
    "prophase",
    "prostaglandin",
    "prostate gland",
    "prostatectomy",
    "prostatitis",
    "protease",
    "protein",
    "protein synthesis",
    "prothrombin",
    "proton",
    "protozoa",
    "proximal",
    "proximal convoluted tubule",
    "psoriasis",
    "ptyalin",
    "puberty",
    "pubis",
    "pulmonary artery",
    "pulmonary embolism",
    "pulmonary semilunar valve",
    "pulmonary veins",
    "pulp cavity",
    "pulse",
    "pulse pressure",
    "pupil",
    "Purkinje fibers",
    "pus",
    "pyelonephritis",
    "pyloric sphincter",
    "pyloric stenosis",
    "pylorospasm",
    "pylorus",
    "pyrexia",
    "pyrogens",
    "pyuria",

];